# Generated by Django 4.2 on 2023-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0002_remove_imunisasi_penyakit_imunisasi_penyakits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imunisasi',
            name='penyakits',
            field=models.ManyToManyField(help_text='Imunisasi ini mencegah penyakit apa saja?', to='apik.penyakit', verbose_name='penyakit'),
        ),
        migrations.AlterField(
            model_name='penyakit',
            name='ilustrasi',
            field=models.ImageField(blank=True, null=True, upload_to='ilustrasi_penyakit/'),
        ),
    ]
