# Generated by Django 4.2 on 2023-04-22 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0003_alter_imunisasi_penyakits_alter_penyakit_ilustrasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bayi',
            options={'verbose_name': 'balita', 'verbose_name_plural': 'balita'},
        ),
        migrations.AddField(
            model_name='imunisasidiberikan',
            name='bidan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imunisasi_dilakukan', to='apik.bidan'),
        ),
    ]
