# Generated by Django 4.2 on 2023-04-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0004_alter_bayi_options_imunisasidiberikan_bidan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imunisasidiberikan',
            options={'ordering': ('tanggal_pemberian',), 'verbose_name': 'imunisasi-balita', 'verbose_name_plural': 'imunisasi-balita'},
        ),
    ]
