# Generated by Django 4.2 on 2023-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0005_alter_imunisasidiberikan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imunisasi',
            name='maksimum_usia',
            field=models.IntegerField(blank=True, help_text='dalam bulan', null=True),
        ),
    ]
