# Generated by Django 4.2.8 on 2024-01-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0007_alter_imunisasidiberikan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imunisasidiberikan',
            name='jam_pencatatan',
            field=models.TimeField(blank=True, null=True, verbose_name='jam pencatatan (WIB)'),
        ),
    ]
