# Generated by Django 4.2.8 on 2024-01-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0008_alter_imunisasidiberikan_jam_pencatatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidan',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
