# Generated by Django 4.2.8 on 2024-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apik', '0009_bidan_nomor_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibu',
            name='nomor_telepon',
            field=models.CharField(blank=True, help_text='format 08XXXXXX...', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bidan',
            name='nomor_telepon',
            field=models.CharField(blank=True, help_text='format 08XXXXXX...', max_length=15, null=True),
        ),
    ]
